// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Ri6ATCba6t_N3I-VqIGyIZRf5VuDNqo',
    appId: '1:888084327427:web:7c742b80f17ddad459b236',
    messagingSenderId: '888084327427',
    projectId: 'combi-web',
    authDomain: 'combi-web.firebaseapp.com',
    storageBucket: 'combi-web.appspot.com',
    measurementId: 'G-4DM8NS1G3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc6BTDz8jyJLOff5MXNrsHq0iTNos8GCY',
    appId: '1:888084327427:android:5c7a79986ae440ed59b236',
    messagingSenderId: '888084327427',
    projectId: 'combi-web',
    storageBucket: 'combi-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl0aj6FEF6RG6zoFM7UP-ksDD_5hMNdwE',
    appId: '1:888084327427:ios:7258176f987ece3759b236',
    messagingSenderId: '888084327427',
    projectId: 'combi-web',
    storageBucket: 'combi-web.appspot.com',
    iosBundleId: 'com.example.combi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl0aj6FEF6RG6zoFM7UP-ksDD_5hMNdwE',
    appId: '1:888084327427:ios:7258176f987ece3759b236',
    messagingSenderId: '888084327427',
    projectId: 'combi-web',
    storageBucket: 'combi-web.appspot.com',
    iosBundleId: 'com.example.combi',
  );

}